# Generated by Django 2.0 on 2019-09-17 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeyStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('current_key', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название локации')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('default', models.BooleanField(default=False, verbose_name='Мстоположения по умолчанию')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сервиса')),
                ('url', models.URLField()),
                ('default', models.BooleanField(default=False, verbose_name='Сервис по умолчанию')),
                ('available_service', models.CharField(choices=[('openweathermap', 'openweathermap')], default='openweathermap', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='apikeystore',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service'),
        ),
    ]
